.TH "CpxMsgPayload" 3 "Sun Jul 11 2021" "CorePartition" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CpxMsgPayload
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CorePartition\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBnThreadID\fP"
.br
.ti -1c
.RI "size_t \fBnAttribute\fP"
.br
.ti -1c
.RI "uint64_t \fBnValue\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "size_t CpxMsgPayload::nAttribute"

.SS "size_t CpxMsgPayload::nThreadID"

.SS "uint64_t CpxMsgPayload::nValue"


.SH "Author"
.PP 
Generated automatically by Doxygen for CorePartition from the source code\&.
