.TH "CpxSmartLock" 3 "Sun Jul 11 2021" "CorePartition" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CpxSmartLock
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CorePartition\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBnSharedLockCount\fP"
.br
.ti -1c
.RI "bool \fBbExclusiveLock\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "bool CpxSmartLock::bExclusiveLock"

.SS "size_t CpxSmartLock::nSharedLockCount"


.SH "Author"
.PP 
Generated automatically by Doxygen for CorePartition from the source code\&.
