.TH "CpxSubscriptions" 3 "Sun Jul 11 2021" "CorePartition" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CpxSubscriptions
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CorePartition\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBTopicCallback\fP \fBcallback\fP"
.br
.ti -1c
.RI "void * \fBpContext\fP"
.br
.ti -1c
.RI "uint16_t \fBnMaxTopics\fP"
.br
.ti -1c
.RI "uint16_t \fBnTopicCount\fP"
.br
.ti -1c
.RI "uint32_t \fBnTopicList\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBTopicCallback\fP CpxSubscriptions::callback"

.SS "uint16_t CpxSubscriptions::nMaxTopics"

.SS "uint16_t CpxSubscriptions::nTopicCount"

.SS "uint32_t CpxSubscriptions::nTopicList"

.SS "void* CpxSubscriptions::pContext"


.SH "Author"
.PP 
Generated automatically by Doxygen for CorePartition from the source code\&.
