//
// main.cpp
// Main file
// ----------------------------------
// Developed with embedXcode+
// https://embedXcode.weebly.com
//
// Project 		Thread_embedXCode
//
// Created by 	GUSTAVO CAMPOS, 10/03/2020 12:48
//              GUSTAVO CAMPOS
//
// Copyright 	© GUSTAVO CAMPOS, 2020
// Licence 		All rights reserved
//
// See 			Thread_embedXCode.ino and ReadMe.txt for references
//
// ----------------------------------
// DO NOT EDIT THIS FILE.
// THE SKETCH IS IN Thread_embedXCode.ino
// ----------------------------------
//
// Last update: Jun 30, 2017 release 7.5.0

// IDE selection
#if defined(EMBEDXCODE)

// Core library and main()
// Minimal proxy main() to be updated at build
#include "Arduino.h"

int main(void)
{
    setup();

    for (;;)
    {
        loop();
    }

    return 0;
}

// Sketch
#include "Thread_embedXCode.ino"


#endif                                                                          // end embedXcode

